import { Badge } from '@/types/gaming';

export const STANDARD_BADGES: Badge[] = [
  {
    id: 'first_transaction',
    name: 'První kroky',
    description: 'Přidej svou první transakci',
    type: 'standard',
    rarity: 'common',
    icon: '🎯',
    color: '#10B981',
    rewardXp: 50,
    rewardCoins: 10,
    passiveBonus: 0,
    condition: 'transactions >= 1',
  },
  {
    id: 'budget_ninja',
    name: 'Budget Ninja',
    description: 'Drž se rozpočtu 30 dní v řadě',
    type: 'standard',
    rarity: 'rare',
    icon: '🥷',
    color: '#8B5CF6',
    rewardXp: 200,
    rewardCoins: 50,
    passiveBonus: 0,
    condition: 'budget_streak >= 30',
  },
  {
    id: 'financial_zen',
    name: 'Finanční zen',
    description: 'Dosáhni pozitivního cash flow 3 měsíce po sobě',
    type: 'standard',
    rarity: 'rare',
    icon: '🧘',
    color: '#06B6D4',
    rewardXp: 300,
    rewardCoins: 75,
    passiveBonus: 0,
    condition: 'positive_cashflow_months >= 3',
  },
  {
    id: 'investor_beginner',
    name: 'Investor začátečník',
    description: 'Proveď svou první investici',
    type: 'standard',
    rarity: 'common',
    icon: '📈',
    color: '#F59E0B',
    rewardXp: 100,
    rewardCoins: 25,
    passiveBonus: 0,
    condition: 'investments >= 1',
  },
  {
    id: 'saver',
    name: 'Šetřič',
    description: 'Našetři 10 000 Kč',
    type: 'standard',
    rarity: 'common',
    icon: '💰',
    color: '#10B981',
    rewardXp: 150,
    rewardCoins: 30,
    passiveBonus: 0,
    condition: 'savings >= 10000',
  },
];

export const EPIC_BADGES: Badge[] = [
  {
    id: 'debt_slayer',
    name: 'Debt Slayer',
    description: '6 měsíců po sobě bez revolving dluhu',
    type: 'epic',
    rarity: 'epic',
    icon: '🦸‍♂️',
    color: '#EF4444',
    rewardXp: 500,
    rewardCoins: 150,
    passiveBonus: 0,
    condition: 'no_revolving_debt_months >= 6',
  },
  {
    id: 'investor_elite',
    name: 'Investor Elite',
    description: '12 měsíců pravidelného DCA',
    type: 'epic',
    rarity: 'epic',
    icon: '💹',
    color: '#8B5CF6',
    rewardXp: 1000,
    rewardCoins: 300,
    passiveBonus: 0.02,
    condition: 'dca_months >= 12',
  },
  {
    id: 'master_planner',
    name: 'Master Planner',
    description: '1 rok s rozpočtem v toleranci ±10%',
    type: 'epic',
    rarity: 'epic',
    icon: '🧠',
    color: '#06B6D4',
    rewardXp: 800,
    rewardCoins: 250,
    passiveBonus: 0,
    condition: 'budget_tolerance_year >= 1',
  },
  {
    id: 'impulse_immunity',
    name: 'Impulse Immunity',
    description: '90 dní bez impulzivního nákupu',
    type: 'epic',
    rarity: 'epic',
    icon: '🔥',
    color: '#F59E0B',
    rewardXp: 600,
    rewardCoins: 200,
    passiveBonus: 0,
    condition: 'no_impulse_days >= 90',
  },
  {
    id: 'community_hero',
    name: 'Community Hero',
    description: '3 výzvy splněné ve veřejných klubech',
    type: 'epic',
    rarity: 'epic',
    icon: '🌍',
    color: '#10B981',
    rewardXp: 250,
    rewardCoins: 100,
    passiveBonus: 0,
    condition: 'club_challenges >= 3',
  },
];

export const LEGACY_BADGES: Badge[] = [
  {
    id: 'founding_buddy',
    name: 'Founding Buddy',
    description: 'Aktivní uživatel 6 měsíců',
    type: 'legacy',
    rarity: 'legendary',
    icon: '🪶',
    color: '#F59E0B',
    rewardXp: 300,
    rewardCoins: 100,
    passiveBonus: 0,
    condition: 'active_months >= 6',
  },
  {
    id: 'year_one_survivor',
    name: 'Year One Survivor',
    description: 'Aktivní rok v kuse',
    type: 'legacy',
    rarity: 'legendary',
    icon: '🕓',
    color: '#8B5CF6',
    rewardXp: 600,
    rewardCoins: 200,
    passiveBonus: 0,
    condition: 'active_months >= 12',
  },
  {
    id: 'veteran_5y',
    name: 'Veteran (5Y)',
    description: '5 let kontinuální aktivity',
    type: 'legacy',
    rarity: 'legendary',
    icon: '💫',
    color: '#06B6D4',
    rewardXp: 1500,
    rewardCoins: 500,
    passiveBonus: 0.05,
    condition: 'active_months >= 60',
  },
  {
    id: 'consistency_king',
    name: 'Consistency King',
    description: '12měsíční streak bez přerušení',
    type: 'legacy',
    rarity: 'legendary',
    icon: '🧩',
    color: '#EF4444',
    rewardXp: 1200,
    rewardCoins: 400,
    passiveBonus: 0,
    condition: 'streak >= 365',
  },
  {
    id: 'financial_sage',
    name: 'Financial Sage',
    description: 'Všechny Epic Badge + aktivní > 1 rok',
    type: 'legacy',
    rarity: 'legendary',
    icon: '🎓',
    color: '#F59E0B',
    rewardXp: 2000,
    rewardCoins: 1000,
    passiveBonus: 0,
    condition: 'all_epic_badges && active_months >= 12',
  },
];

export const META_QUESTS_BADGES: Badge[] = [
  {
    id: 'emergency_fund_master',
    name: 'Emergency Fund Master',
    description: 'Dokončil meta-výzvu "Cesta k rezervě"',
    type: 'meta',
    rarity: 'epic',
    icon: '🛡️',
    color: '#10B981',
    rewardXp: 500,
    rewardCoins: 150,
    passiveBonus: 0,
    condition: 'meta_quest_emergency_fund',
  },
  {
    id: 'year_investor',
    name: 'Rok investora',
    description: 'Dokončil meta-výzvu "Rok investora"',
    type: 'meta',
    rarity: 'epic',
    icon: '📊',
    color: '#8B5CF6',
    rewardXp: 1000,
    rewardCoins: 300,
    passiveBonus: 0.03,
    condition: 'meta_quest_year_investor',
  },
  {
    id: 'minimalist_champion',
    name: 'Minimalist Champion',
    description: 'Dokončil meta-výzvu "Minimalist Challenge"',
    type: 'meta',
    rarity: 'epic',
    icon: '✨',
    color: '#06B6D4',
    rewardXp: 400,
    rewardCoins: 120,
    passiveBonus: 0,
    condition: 'meta_quest_minimalist',
  },
];

export const ALL_BADGES: Badge[] = [
  ...STANDARD_BADGES,
  ...EPIC_BADGES,
  ...LEGACY_BADGES,
  ...META_QUESTS_BADGES,
];
