/** Klíče pro tip dne (shodné s překlady `dailyTip1`…`dailyTip30`). */
export const DAILY_TIP_KEYS = [
  'dailyTip1',
  'dailyTip2',
  'dailyTip3',
  'dailyTip4',
  'dailyTip5',
  'dailyTip6',
  'dailyTip7',
  'dailyTip8',
  'dailyTip9',
  'dailyTip10',
  'dailyTip11',
  'dailyTip12',
  'dailyTip13',
  'dailyTip14',
  'dailyTip15',
  'dailyTip16',
  'dailyTip17',
  'dailyTip18',
  'dailyTip19',
  'dailyTip20',
  'dailyTip21',
  'dailyTip22',
  'dailyTip23',
  'dailyTip24',
  'dailyTip25',
  'dailyTip26',
  'dailyTip27',
  'dailyTip28',
  'dailyTip29',
  'dailyTip30',
] as const;

export type DailyTipKey = (typeof DAILY_TIP_KEYS)[number];
