import { Quest, MetaQuest } from '@/types/gaming';

export const DAILY_QUESTS: Omit<Quest, 'id' | 'progress' | 'completed' | 'completedAt' | 'expiresAt'>[] = [
  {
    title: 'Denní kontrola',
    description: 'Zkontroluj své finance dnes',
    type: 'daily',
    icon: '📊',
    color: '#10B981',
    maxProgress: 1,
    rewardXp: 10,
    rewardCoins: 5,
  },
  {
    title: 'Přidej transakci',
    description: 'Zaznamenej alespoň 1 transakci dnes',
    type: 'daily',
    icon: '💳',
    color: '#8B5CF6',
    maxProgress: 1,
    rewardXp: 15,
    rewardCoins: 5,
  },
  {
    title: 'Tip dne',
    description: 'Přečti si dnešní finanční tip',
    type: 'daily',
    icon: '💡',
    color: '#F59E0B',
    maxProgress: 1,
    rewardXp: 5,
    rewardCoins: 2,
  },
];

export const WEEKLY_QUESTS: Omit<Quest, 'id' | 'progress' | 'completed' | 'completedAt' | 'expiresAt'>[] = [
  {
    title: 'Týdenní přehled',
    description: 'Zkontroluj své výdaje za týden',
    type: 'weekly',
    icon: '📈',
    color: '#06B6D4',
    maxProgress: 1,
    rewardXp: 50,
    rewardCoins: 20,
  },
  {
    title: 'Aktivní týden',
    description: 'Přidej transakce 5 dní v týdnu',
    type: 'weekly',
    icon: '🔥',
    color: '#EF4444',
    maxProgress: 5,
    rewardXp: 75,
    rewardCoins: 30,
  },
  {
    title: 'Šetřič',
    description: 'Ušetři alespoň 500 Kč tento týden',
    type: 'weekly',
    icon: '💰',
    color: '#10B981',
    maxProgress: 500,
    rewardXp: 100,
    rewardCoins: 40,
  },
];

export const MONTHLY_QUESTS: Omit<Quest, 'id' | 'progress' | 'completed' | 'completedAt' | 'expiresAt'>[] = [
  {
    title: 'Měsíční bilance',
    description: 'Ukonči měsíc s pozitivním cash flow',
    type: 'monthly',
    icon: '💹',
    color: '#8B5CF6',
    maxProgress: 1,
    rewardXp: 200,
    rewardCoins: 100,
  },
  {
    title: 'Rozpočtový mistr',
    description: 'Drž se rozpočtu celý měsíc (±10%)',
    type: 'monthly',
    icon: '🎯',
    color: '#06B6D4',
    maxProgress: 1,
    rewardXp: 250,
    rewardCoins: 120,
  },
  {
    title: 'Investor',
    description: 'Investuj alespoň 1000 Kč tento měsíc',
    type: 'monthly',
    icon: '📊',
    color: '#F59E0B',
    maxProgress: 1000,
    rewardXp: 300,
    rewardCoins: 150,
  },
];

export const META_QUESTS: MetaQuest[] = [
  {
    id: 'emergency_fund_journey',
    title: 'Cesta k rezervě',
    description: 'Vytvoř si emergency fond během 5 týdnů',
    icon: '🛡️',
    color: '#10B981',
    subQuests: [
      'emergency_week1',
      'emergency_week2',
      'emergency_week3',
      'emergency_week4',
      'emergency_week5',
    ],
    completedSubQuests: [],
    rewardBadgeId: 'emergency_fund_master',
    rewardXp: 500,
    rewardCoins: 200,
    completed: false,
  },
  {
    id: 'year_investor_journey',
    title: 'Rok investora',
    description: 'Investuj pravidelně 12 měsíců v řadě',
    icon: '📊',
    color: '#8B5CF6',
    subQuests: [
      'invest_month_1',
      'invest_month_2',
      'invest_month_3',
      'invest_month_4',
      'invest_month_5',
      'invest_month_6',
      'invest_month_7',
      'invest_month_8',
      'invest_month_9',
      'invest_month_10',
      'invest_month_11',
      'invest_month_12',
    ],
    completedSubQuests: [],
    rewardBadgeId: 'year_investor',
    rewardXp: 1000,
    rewardCoins: 400,
    completed: false,
  },
  {
    id: 'minimalist_challenge',
    title: 'Minimalist Challenge',
    description: 'Zjednoduš své finance a život',
    icon: '✨',
    color: '#06B6D4',
    subQuests: [
      'minimalist_reduce_expenses',
      'minimalist_sell_unused',
      'minimalist_budget_plan',
    ],
    completedSubQuests: [],
    rewardBadgeId: 'minimalist_champion',
    rewardXp: 400,
    rewardCoins: 150,
    completed: false,
  },
];
