import { Quest, MetaQuest } from '@/types/gaming';

export const DAILY_QUESTS: Omit<Quest, 'id' | 'progress' | 'completed' | 'completedAt' | 'expiresAt'>[] = [
  {
    title: 'Denní kontrola',
    description: 'Zkontroluj své finance dnes',
    type: 'daily',
    icon: '📊',
    color: '#10B981',
    maxProgress: 1,
    rewardXp: 10,
    rewardCoins: 5,
  },
  {
    title: 'Přidej transakci',
    description: 'Zaznamenej alespoň 1 transakci dnes',
    type: 'daily',
    icon: '💳',
    color: '#8B5CF6',
    maxProgress: 1,
    rewardXp: 15,
    rewardCoins: 5,
  },
  {
    title: 'Tip dne',
    description: 'Přečti si dnešní finanční tip',
    type: 'daily',
    icon: '💡',
    color: '#F59E0B',
    maxProgress: 1,
    rewardXp: 5,
    rewardCoins: 2,
  },
  {
    title: 'Ranní start',
    description: 'Otevři aplikaci před 9:00',
    type: 'daily',
    icon: '🌅',
    color: '#F97316',
    maxProgress: 1,
    rewardXp: 8,
    rewardCoins: 3,
  },
  {
    title: 'Kontrola rozpočtu',
    description: 'Zkontroluj, jak jsi na tom s rozpočtem',
    type: 'daily',
    icon: '🎯',
    color: '#06B6D4',
    maxProgress: 1,
    rewardXp: 12,
    rewardCoins: 6,
  },
  {
    title: 'Žádné impulzivní nákupy',
    description: 'Projdi den bez impulzivního nákupu',
    type: 'daily',
    icon: '🛡️',
    color: '#14B8A6',
    maxProgress: 1,
    rewardXp: 20,
    rewardCoins: 10,
  },
  {
    title: 'Přidej 3 transakce',
    description: 'Zaznamenej alespoň 3 transakce dnes',
    type: 'daily',
    icon: '📝',
    color: '#A855F7',
    maxProgress: 3,
    rewardXp: 25,
    rewardCoins: 12,
  },
  {
    title: 'Zkontroluj investice',
    description: 'Podívej se na své portfolio',
    type: 'daily',
    icon: '📈',
    color: '#3B82F6',
    maxProgress: 1,
    rewardXp: 10,
    rewardCoins: 5,
  },
  {
    title: 'Chat s BuddyBotem',
    description: 'Zeptej se BuddyBota na finanční radu',
    type: 'daily',
    icon: '🤖',
    color: '#EC4899',
    maxProgress: 1,
    rewardXp: 15,
    rewardCoins: 8,
  },
  {
    title: 'Porovnej s kamarády',
    description: 'Podívej se na žebříček přátel',
    type: 'daily',
    icon: '👥',
    color: '#8B5CF6',
    maxProgress: 1,
    rewardXp: 10,
    rewardCoins: 5,
  },
  {
    title: 'Zkontroluj závazky',
    description: 'Projdi si své půjčky a hypotéky',
    type: 'daily',
    icon: '🏦',
    color: '#EF4444',
    maxProgress: 1,
    rewardXp: 12,
    rewardCoins: 6,
  },
  {
    title: 'Večerní bilance',
    description: 'Zkontroluj finance před spaním',
    type: 'daily',
    icon: '🌙',
    color: '#6366F1',
    maxProgress: 1,
    rewardXp: 8,
    rewardCoins: 4,
  },
  {
    title: 'Ušetři dnes',
    description: 'Ušetři alespoň 50 Kč dnes',
    type: 'daily',
    icon: '🐷',
    color: '#F472B6',
    maxProgress: 50,
    rewardXp: 18,
    rewardCoins: 9,
  },
  {
    title: 'Žádné zbytečné výdaje',
    description: 'Vyhni se zbytečným výdajům dnes',
    type: 'daily',
    icon: '✨',
    color: '#10B981',
    maxProgress: 1,
    rewardXp: 15,
    rewardCoins: 7,
  },
  {
    title: 'Přečti si lekci',
    description: 'Nauč se něco nového v sekci Vzdělávání',
    type: 'daily',
    icon: '📚',
    color: '#F59E0B',
    maxProgress: 1,
    rewardXp: 20,
    rewardCoins: 10,
  },
];

export const WEEKLY_QUESTS: Omit<Quest, 'id' | 'progress' | 'completed' | 'completedAt' | 'expiresAt'>[] = [
  {
    title: 'Týdenní přehled',
    description: 'Zkontroluj své výdaje za týden',
    type: 'weekly',
    icon: '📈',
    color: '#06B6D4',
    maxProgress: 1,
    rewardXp: 50,
    rewardCoins: 20,
  },
  {
    title: 'Aktivní týden',
    description: 'Přidej transakce 5 dní v týdnu',
    type: 'weekly',
    icon: '🔥',
    color: '#EF4444',
    maxProgress: 5,
    rewardXp: 75,
    rewardCoins: 30,
  },
  {
    title: 'Šetřič',
    description: 'Ušetři alespoň 500 Kč tento týden',
    type: 'weekly',
    icon: '💰',
    color: '#10B981',
    maxProgress: 500,
    rewardXp: 100,
    rewardCoins: 40,
  },
  {
    title: 'Týdenní streak',
    description: 'Otevři aplikaci každý den tento týden',
    type: 'weekly',
    icon: '⚡',
    color: '#F59E0B',
    maxProgress: 7,
    rewardXp: 120,
    rewardCoins: 50,
  },
  {
    title: 'Rozpočtový týden',
    description: 'Drž se rozpočtu celý týden (±15%)',
    type: 'weekly',
    icon: '🎯',
    color: '#8B5CF6',
    maxProgress: 1,
    rewardXp: 90,
    rewardCoins: 35,
  },
  {
    title: 'Žádné dluhy',
    description: 'Nesplať žádný nový dluh tento týden',
    type: 'weekly',
    icon: '🛡️',
    color: '#14B8A6',
    maxProgress: 1,
    rewardXp: 80,
    rewardCoins: 30,
  },
  {
    title: 'Investiční týden',
    description: 'Investuj alespoň 200 Kč tento týden',
    type: 'weekly',
    icon: '📊',
    color: '#3B82F6',
    maxProgress: 200,
    rewardXp: 110,
    rewardCoins: 45,
  },
  {
    title: 'Vzdělávací týden',
    description: 'Přečti si 3 lekce tento týden',
    type: 'weekly',
    icon: '📚',
    color: '#F97316',
    maxProgress: 3,
    rewardXp: 85,
    rewardCoins: 35,
  },
  {
    title: 'Sociální týden',
    description: 'Přidej 2 nové přátele',
    type: 'weekly',
    icon: '👥',
    color: '#EC4899',
    maxProgress: 2,
    rewardXp: 70,
    rewardCoins: 28,
  },
  {
    title: 'Minimalistický týden',
    description: 'Utrať méně než minulý týden',
    type: 'weekly',
    icon: '✨',
    color: '#10B981',
    maxProgress: 1,
    rewardXp: 95,
    rewardCoins: 38,
  },
  {
    title: 'Týdenní úspory',
    description: 'Ušetři alespoň 1000 Kč tento týden',
    type: 'weekly',
    icon: '💎',
    color: '#A855F7',
    maxProgress: 1000,
    rewardXp: 150,
    rewardCoins: 60,
  },
  {
    title: 'Kontrola portfolia',
    description: 'Zkontroluj investice 3x tento týden',
    type: 'weekly',
    icon: '📈',
    color: '#06B6D4',
    maxProgress: 3,
    rewardXp: 65,
    rewardCoins: 25,
  },
  {
    title: 'Týdenní plánování',
    description: 'Naplánuj si rozpočet na příští týden',
    type: 'weekly',
    icon: '📅',
    color: '#6366F1',
    maxProgress: 1,
    rewardXp: 60,
    rewardCoins: 24,
  },
  {
    title: 'Bez impulzivních nákupů',
    description: 'Projdi celý týden bez impulzivního nákupu',
    type: 'weekly',
    icon: '🧘',
    color: '#14B8A6',
    maxProgress: 1,
    rewardXp: 130,
    rewardCoins: 52,
  },
  {
    title: 'Týdenní transakce',
    description: 'Zaznamenej alespoň 20 transakcí',
    type: 'weekly',
    icon: '📝',
    color: '#F59E0B',
    maxProgress: 20,
    rewardXp: 100,
    rewardCoins: 40,
  },
];

export const MONTHLY_QUESTS: Omit<Quest, 'id' | 'progress' | 'completed' | 'completedAt' | 'expiresAt'>[] = [
  {
    title: 'Měsíční bilance',
    description: 'Ukonči měsíc s pozitivním cash flow',
    type: 'monthly',
    icon: '💹',
    color: '#8B5CF6',
    maxProgress: 1,
    rewardXp: 200,
    rewardCoins: 100,
  },
  {
    title: 'Rozpočtový mistr',
    description: 'Drž se rozpočtu celý měsíc (±10%)',
    type: 'monthly',
    icon: '🎯',
    color: '#06B6D4',
    maxProgress: 1,
    rewardXp: 250,
    rewardCoins: 120,
  },
  {
    title: 'Investor',
    description: 'Investuj alespoň 1000 Kč tento měsíc',
    type: 'monthly',
    icon: '📊',
    color: '#F59E0B',
    maxProgress: 1000,
    rewardXp: 300,
    rewardCoins: 150,
  },
  {
    title: 'Měsíční streak',
    description: 'Otevři aplikaci každý den celý měsíc',
    type: 'monthly',
    icon: '🔥',
    color: '#EF4444',
    maxProgress: 30,
    rewardXp: 400,
    rewardCoins: 200,
  },
  {
    title: 'Spořivý měsíc',
    description: 'Ušetři alespoň 5000 Kč tento měsíc',
    type: 'monthly',
    icon: '💰',
    color: '#10B981',
    maxProgress: 5000,
    rewardXp: 350,
    rewardCoins: 175,
  },
  {
    title: 'Bez dluhů',
    description: 'Projdi celý měsíc bez nových dluhů',
    type: 'monthly',
    icon: '🛡️',
    color: '#14B8A6',
    maxProgress: 1,
    rewardXp: 280,
    rewardCoins: 140,
  },
  {
    title: 'Měsíční vzdělávání',
    description: 'Přečti si 10 lekcí tento měsíc',
    type: 'monthly',
    icon: '📚',
    color: '#F97316',
    maxProgress: 10,
    rewardXp: 320,
    rewardCoins: 160,
  },
  {
    title: 'Portfolio růst',
    description: 'Zvyš hodnotu portfolia o 5% tento měsíc',
    type: 'monthly',
    icon: '📈',
    color: '#3B82F6',
    maxProgress: 1,
    rewardXp: 380,
    rewardCoins: 190,
  },
  {
    title: 'Měsíční transakce',
    description: 'Zaznamenej alespoň 100 transakcí',
    type: 'monthly',
    icon: '📝',
    color: '#A855F7',
    maxProgress: 100,
    rewardXp: 300,
    rewardCoins: 150,
  },
  {
    title: 'Minimalistický měsíc',
    description: 'Utrať o 20% méně než minulý měsíc',
    type: 'monthly',
    icon: '✨',
    color: '#EC4899',
    maxProgress: 1,
    rewardXp: 330,
    rewardCoins: 165,
  },
  {
    title: 'Sociální měsíc',
    description: 'Přidej 5 nových přátel',
    type: 'monthly',
    icon: '👥',
    color: '#6366F1',
    maxProgress: 5,
    rewardXp: 260,
    rewardCoins: 130,
  },
  {
    title: 'Měsíční cíle',
    description: 'Splň všechny své finanční cíle',
    type: 'monthly',
    icon: '🎯',
    color: '#10B981',
    maxProgress: 1,
    rewardXp: 420,
    rewardCoins: 210,
  },
  {
    title: 'DCA Investor',
    description: 'Investuj pravidelně každý týden',
    type: 'monthly',
    icon: '💎',
    color: '#8B5CF6',
    maxProgress: 4,
    rewardXp: 360,
    rewardCoins: 180,
  },
  {
    title: 'Emergency fond',
    description: 'Vytvoř si rezervu na 3 měsíce',
    type: 'monthly',
    icon: '🏦',
    color: '#06B6D4',
    maxProgress: 1,
    rewardXp: 500,
    rewardCoins: 250,
  },
  {
    title: 'Měsíční analýza',
    description: 'Zkontroluj měsíční report 3x',
    type: 'monthly',
    icon: '📊',
    color: '#F59E0B',
    maxProgress: 3,
    rewardXp: 240,
    rewardCoins: 120,
  },
  {
    title: 'Bez impulzivních nákupů',
    description: 'Projdi celý měsíc bez impulzivního nákupu',
    type: 'monthly',
    icon: '🧘',
    color: '#14B8A6',
    maxProgress: 1,
    rewardXp: 450,
    rewardCoins: 225,
  },
  {
    title: 'Měsíční úspěch',
    description: 'Dosáhni Buddy Score 1000+',
    type: 'monthly',
    icon: '🏆',
    color: '#F59E0B',
    maxProgress: 1,
    rewardXp: 400,
    rewardCoins: 200,
  },
  {
    title: 'Diverzifikace',
    description: 'Investuj do alespoň 5 různých aktiv',
    type: 'monthly',
    icon: '🌍',
    color: '#10B981',
    maxProgress: 5,
    rewardXp: 340,
    rewardCoins: 170,
  },
  {
    title: 'Měsíční plánování',
    description: 'Naplánuj si rozpočet na příští měsíc',
    type: 'monthly',
    icon: '📅',
    color: '#A855F7',
    maxProgress: 1,
    rewardXp: 220,
    rewardCoins: 110,
  },
  {
    title: 'Finanční svoboda',
    description: 'Dosáhni pasivního příjmu 1000 Kč/měsíc',
    type: 'monthly',
    icon: '🌟',
    color: '#EC4899',
    maxProgress: 1,
    rewardXp: 600,
    rewardCoins: 300,
  },
];

export const META_QUESTS: MetaQuest[] = [
  {
    id: 'emergency_fund_journey',
    title: 'Cesta k rezervě',
    description: 'Vytvoř si emergency fond během 5 týdnů',
    icon: '🛡️',
    color: '#10B981',
    subQuests: [
      'emergency_week1',
      'emergency_week2',
      'emergency_week3',
      'emergency_week4',
      'emergency_week5',
    ],
    completedSubQuests: [],
    rewardBadgeId: 'emergency_fund_master',
    rewardXp: 500,
    rewardCoins: 200,
    completed: false,
  },
  {
    id: 'year_investor_journey',
    title: 'Rok investora',
    description: 'Investuj pravidelně 12 měsíců v řadě',
    icon: '📊',
    color: '#8B5CF6',
    subQuests: [
      'invest_month_1',
      'invest_month_2',
      'invest_month_3',
      'invest_month_4',
      'invest_month_5',
      'invest_month_6',
      'invest_month_7',
      'invest_month_8',
      'invest_month_9',
      'invest_month_10',
      'invest_month_11',
      'invest_month_12',
    ],
    completedSubQuests: [],
    rewardBadgeId: 'year_investor',
    rewardXp: 1000,
    rewardCoins: 400,
    completed: false,
  },
  {
    id: 'minimalist_challenge',
    title: 'Minimalist Challenge',
    description: 'Zjednoduš své finance a život',
    icon: '✨',
    color: '#06B6D4',
    subQuests: [
      'minimalist_reduce_expenses',
      'minimalist_sell_unused',
      'minimalist_budget_plan',
    ],
    completedSubQuests: [],
    rewardBadgeId: 'minimalist_champion',
    rewardXp: 400,
    rewardCoins: 150,
    completed: false,
  },
];
