import { Platform, StyleSheet } from 'react-native';

export const householdStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F8FAFC' },
  setupWrap: { paddingBottom: 32 },
  setupHeader: { margin: 20, borderRadius: 16, padding: 20 },
  setupTitle: { color: 'white', fontSize: 28, fontWeight: 'bold' },
  setupSubtitle: { color: 'white', fontSize: 14, opacity: 0.9, marginTop: 8 },
  setupCard: {
    marginHorizontal: 20,
    marginTop: 12,
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  setupCardTitle: { fontSize: 18, fontWeight: '700', color: '#1F2937', marginBottom: 10 },
  header: { paddingTop: 60, paddingBottom: 24, paddingHorizontal: 20 },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1, marginRight: 12 },
  headerTitleActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerRenameBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { fontSize: 28, fontWeight: 'bold', color: 'white', flexShrink: 1 },
  householdNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
  },
  householdNavHit: {
    padding: 4,
    minWidth: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  householdNavHitDisabled: { opacity: 0.35 },
  householdNavCenter: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 8,
  },
  householdNavTitleHit: {
    flexShrink: 1,
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  householdNavTitle: {
    flexShrink: 1,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
    color: 'white',
  },
  overviewCard: {
    marginTop: 16,
    borderRadius: 16,
    padding: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  overviewLabel: { color: 'white', opacity: 0.9, fontSize: 12, fontWeight: '600' },
  overviewTotal: { color: 'white', fontSize: 28, fontWeight: '800', marginTop: 2, lineHeight: 32 },
  overviewTotalMedium: { letterSpacing: -0.5, marginBottom: 0 },
  overviewDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(255,255,255,0.28)',
    marginVertical: 8,
  },
  overviewTwoCol: {
    flexDirection: 'row',
    gap: 8,
  },
  overviewCol: { flex: 1, minWidth: 0 },
  overviewColRight: { alignItems: 'flex-end' },
  overviewColLabel: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 10,
    fontWeight: '500',
    marginBottom: 2,
    lineHeight: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.25,
  },
  overviewColLabelRight: { textAlign: 'right' },
  overviewColValue: {
    color: 'white',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: -0.2,
    lineHeight: 18,
  },
  overviewColValueRight: { textAlign: 'right' },
  overviewPaidPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 5,
    marginTop: 6,
    marginBottom: 8,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  overviewPaidPillText: { color: 'rgba(255,255,255,0.95)', fontSize: 11, fontWeight: '600', lineHeight: 14 },
  overviewSinglePayerRow: {
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  overviewSinglePayerText: {
    flex: 1,
    color: 'rgba(255,255,255,0.92)',
    fontSize: 12,
    fontWeight: '600',
  },
  overviewSinglePayerLink: {
    color: 'rgba(255,255,255,0.95)',
    fontSize: 12,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  overviewSubBox: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    padding: 10,
    marginBottom: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  overviewSubBoxLast: { marginBottom: 0 },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.25)',
    overflow: 'hidden',
    marginTop: 8,
    marginBottom: 2,
  },
  switcherBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  switcherSheet: {
    borderRadius: 16,
    padding: 16,
    maxHeight: '70%',
    zIndex: 1,
  },
  switcherSheetTitle: { fontSize: 18, fontWeight: '700', marginBottom: 12 },
  switcherList: { maxHeight: 360 },
  switcherRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    marginBottom: 8,
  },
  switcherRowMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 4,
    paddingHorizontal: 2,
    minWidth: 0,
  },
  switcherRowEmoji: { fontSize: 20 },
  switcherRowLabel: { flex: 1, fontSize: 16, fontWeight: '600' },
  switcherIconBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  switcherCreateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    marginTop: 4,
  },
  switcherCreateText: { fontSize: 15, fontWeight: '700' },
  inviteSheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  inviteSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 28,
  },
  inviteSheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#CBD5E1',
    marginBottom: 12,
  },
  inviteSheetHint: { fontSize: 14, lineHeight: 20, marginBottom: 16 },
  inviteSheetCode: {
    fontSize: 36,
    fontWeight: '800',
    letterSpacing: Platform.OS === 'ios' ? 4 : 0,
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 8,
  },
  inviteShareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  inviteToggleRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 14 },
  inviteToggleBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inviteToggleLabel: { flex: 1, fontSize: 14, lineHeight: 20 },
  notifBanner: {
    marginHorizontal: 20,
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
  },
  notifBannerText: { fontSize: 13, color: '#64748B', textAlign: 'center', lineHeight: 18 },
  section: { marginHorizontal: 20, marginTop: 20 },
  expenseTabBar: {
    flexDirection: 'row',
    marginBottom: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  expenseTab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  expenseTabText: {
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  expenseTabTextActive: {
    fontWeight: '800',
  },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  sectionTitle: { fontSize: 20, fontWeight: '700', color: '#1F2937' },
  sectionAction: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  sectionActionText: { color: '#667eea', fontWeight: '700', fontSize: 14 },
  card: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 12,
  },
  cardTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
  cardRightGroup: { alignItems: 'flex-end', gap: 8 },
  deleteIconButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEE2E2',
  },
  cardTitle: { fontSize: 16, fontWeight: '700', color: '#1F2937' },
  cardMeta: { fontSize: 13, color: '#6B7280', marginTop: 2 },
  cardAmount: { fontSize: 16, fontWeight: '700', color: '#111827' },
  cardBottomRow: { marginTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statusBadge: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  statusText: { fontSize: 13, fontWeight: '700' },
  markPaidButton: { backgroundColor: '#EEF2FF', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8 },
  markPaidButtonText: { color: '#4F46E5', fontSize: 12, fontWeight: '700' },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  modalBackdropPressable: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  modalSheetCard: {
    maxHeight: '92%',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 20,
    paddingBottom: 32,
    width: '100%',
    zIndex: 1,
    elevation: 12,
  },
  modalSheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#D1D5DB',
    marginTop: 10,
    marginBottom: 6,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  modalHeaderSpacer: { width: 28, height: 28 },
  modalTitleInHeader: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
    textAlign: 'center',
  },
  modalScrollContent: { paddingBottom: 24 },
  input: {
    backgroundColor: 'white',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    fontSize: 16,
    color: '#1F2937',
    marginBottom: 10,
  },
  fieldLabel: { fontSize: 14, fontWeight: '600', color: '#374151', marginBottom: 6 },
  fieldLabelCategory: { marginTop: 4 },
  recurringFrequencyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  recurringCategoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  recurringCategoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    gap: 6,
  },
  recurringCategoryPillIdle: { backgroundColor: '#F3F4F6' },
  recurringCategoryPillSelected: { backgroundColor: '#667eea' },
  recurringCategoryPillEmoji: { fontSize: 16 },
  recurringCategoryPillLabel: { fontSize: 13, fontWeight: '600', color: '#1F2937' },
  recurringCategoryPillLabelSelected: { color: '#FFFFFF' },
  recurringCategoryPillCheck: { marginLeft: 2 },
  recurringCategoryPillAddCustom: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#667eea',
    borderStyle: 'dashed',
  },
  recurringCategoryPillAddCustomText: { fontSize: 13, fontWeight: '700', color: '#667eea' },
  customCategoryOverlay: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  customCategoryBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  customCategoryDialog: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    maxWidth: 400,
    alignSelf: 'center',
    width: '100%',
    zIndex: 1,
    elevation: 8,
  },
  emojiGridScroll: { maxHeight: 220, marginBottom: 16 },
  emojiGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  emojiCell: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  emojiCellSelected: { borderColor: '#4F46E5', backgroundColor: '#EEF2FF' },
  emojiCellText: { fontSize: 22 },
  primaryButton: { marginTop: 16, backgroundColor: '#667eea', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  primaryButtonText: { color: 'white', fontWeight: '700', fontSize: 16 },
  secondaryButton: { marginTop: 10, backgroundColor: '#E5E7EB', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  secondaryButtonText: { color: '#374151', fontWeight: '700', fontSize: 16 },
  recurringMyShareLine: { fontSize: 13, marginTop: 6 },
  recurringDueBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 8,
  },
  recurringDueBadgeText: { fontSize: 12, fontWeight: '600' },
  sharedMonthNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    paddingVertical: 10,
    paddingHorizontal: 8,
    marginBottom: 12,
  },
  sharedMonthArrow: { padding: 6 },
  sharedMonthLabel: { fontSize: 15, fontWeight: '700', textTransform: 'capitalize' },
  sharedEmpty: { fontSize: 14, lineHeight: 20, marginBottom: 8 },
  sharedTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  sharedReceiptIcon: { fontSize: 18 },
  sharedReceiptAttachBtn: {
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sharedReceiptAttachBtnText: { fontSize: 15, fontWeight: '600' },
  sharedReceiptPreviewWrap: {
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 12,
    overflow: 'hidden',
    padding: 10,
    gap: 8,
  },
  sharedReceiptPreview: { width: '100%', height: 160, borderRadius: 8 },
  sharedReceiptPreviewHint: { fontSize: 13, fontWeight: '600' },
  receiptFsRoot: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center',
    padding: 16,
  },
  receiptFsClose: { position: 'absolute', top: 52, right: 16, zIndex: 2, padding: 8 },
  receiptFsCloseText: { color: 'white', fontSize: 17, fontWeight: '600' },
  receiptFsImage: { width: '100%', flex: 1, minHeight: 400 },
  sharedBadgeRow: { flexDirection: 'row', marginTop: 8 },
  sharedSplitBadge: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4 },
  sharedSplitBadgeText: { fontSize: 12, fontWeight: '700' },
  sharedPayerRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 14 },
  sharedPayerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sharedPayerAvatarText: { fontSize: 12, fontWeight: '800' },
  sharedPayerLabel: { fontSize: 13 },
  sharedDateButton: { justifyContent: 'center' },
  recurringPaidChecksRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
    paddingHorizontal: 2,
  },
  recurringPaidChecksRowCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
    gap: 6,
  },
  multiOccSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  multiOccSummaryText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
  },
  occurrenceRowCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 44,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  occurrenceDateCompact: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    marginRight: 10,
  },
  recurringPaidCheckColumn: {
    alignItems: 'center',
    minWidth: 52,
    paddingVertical: 4,
  },
  recurringPaidCheckColumnCompact: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  recurringPaidCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recurringPaidCircleCompact: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recurringPaidRoleLabel: { marginTop: 6, fontSize: 12, fontWeight: '600' },
  recurringProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 14,
  },
  recurringItemProgressTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    overflow: 'hidden',
  },
  recurringItemProgressFill: {
    height: '100%',
    borderRadius: 3,
  },
  recurringProgressPercent: { fontSize: 12, fontWeight: '700', minWidth: 36, textAlign: 'right' },
  recurringSplitRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  recurringSplitPill: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
  },
  recurringSplitPillText: { fontSize: 12, fontWeight: '600', textAlign: 'center' },
  singlePayerInfoRow: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  singlePayerInfoText: { fontSize: 13, fontWeight: '600' },
  settlementCard: {
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 16,
    marginBottom: 16,
  },
  settlementSectionTitle: { fontSize: 16, fontWeight: '800', marginBottom: 10 },
  settlementScopeHint: { fontSize: 12, fontWeight: '600', marginBottom: 10, marginTop: -4 },
  settlementSettledRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  settlementSettledText: { fontSize: 15, fontWeight: '700' },
  settlementDebtRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
  },
  settlementDebtText: { flex: 1, fontSize: 14, fontWeight: '600' },
  settlementSettleBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  settlementSettleBtnText: { fontSize: 13, fontWeight: '700' },
  settlementHistoryToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    paddingTop: 10,
  },
  settlementHistoryToggleText: { fontSize: 14, fontWeight: '700' },
  settlementHistoryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  settlementHistoryMain: { fontSize: 13, fontWeight: '600' },
  settlementHistoryNote: { fontSize: 12, marginTop: 4 },
  settleConfirmCard: {
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 20,
    maxWidth: 420,
    alignSelf: 'center',
    width: '100%',
  },
});

